/* tslint:disable */
/* eslint-disable */
/**
 * StampWallet API Server
 * StampWallet API Server REST Specification
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: fbstachura@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

